### ISSUE TITLE
Problem when REST Module is not installed

### ISSUE THREAD

**Issue by luke-** [humhub/mail#221]
After update the `mail` module without `rest` module installed, following error appear when calling yii cli.

```
Exception 'Error' with message 'Class 'humhub\modules\rest\components\BaseController' not found'

in /srv/www/htdocs/testvic/modules/mail/controllers/rest/MessageController.php:23

Stack trace:
#0 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include()
#1 [internal function]: yii\BaseYii::autoload('humhub\\modules\\...')
#2 [internal function]: spl_autoload_call('humhub\\modules\\...')
#3 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(279): class_exists('humhub\\modules\\...')
#4 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(257): yii\console\controllers\HelpController->validateControllerClass('humhub\\modules\\...')
#5 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(240): yii\console\controllers\HelpController->getModuleCommands(Object(humhub\modules\mail\Module))
#6 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(172): yii\console\controllers\HelpController->getModuleCommands(Object(humhub\components\console\Application))
#7 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(192): yii\console\controllers\HelpController->getCommands()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(292): yii\console\controllers\HelpController->getCommandDescriptions()
#9 /srv/humhub/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#10 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /srv/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('', Array)
#14 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('', Array)
#15 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('', Array)
#16 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('', Array)
#17 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#18 /srv/www/htdocs/testvic/yii.php(38): yii\base\Application->run()
```

**Comment by yurabakhtin** [comment]
@luke- The error appears if file of the class `humhub\modules\rest\components\BaseController` doesn't exist on disk.

Currently we have the code:

```php
use humhub\modules\rest\components\BaseController;

class MessageController extends BaseController
{
    ...
}
```

The error appears when Yii tries to create a list of commands from all files ended with `*Controller.php`.

I found a solution:

```php
use humhub\modules\rest\components\BaseController;

if (class_exists('\humhub\modules\rest\components\BaseController')) {
    class RestController extends BaseController { }
} else {
    class RestController { }
}

class MessageController extends RestController
{
    ...
}
```

but in order to apply this solution we should decide where to create a file `RestController.php` for the middle class:

1) in each module folder `protected/modules/module-folder/controllers/rest/RestController.php`, but we should this file in each module where REST API is used.
2) in core folder, probably here `protected/humhub/controllers/RestController.php`, do you agree this?

**Comment by yurabakhtin** [comment]
@luke- Fixed in 5 modules as we discussed in chat:

- mail - PR https://github.com/humhub/mail/pull/222
- wiki - PR https://github.com/humhub/wiki/pull/168
- tasks - PR https://github.com/humhub/tasks/pull/142
- calendar - PR https://github.com/humhub/calendar/pull/237
- cfiles - Commit https://github.com/humhub/cfiles/pull/111/commits/6ea2d722fd7ce90fa35ca57958a6fdfad6df9eea - I did this as commit because the PR was not merged yet.

**Comment by luke-** [comment]
Thanks!
