### ISSUE TITLE
Conversations not loading - TypeError in InboxMessagePreview widget

### ISSUE THREAD

**Issue by marc-farre** [humhub/mail#404]
Original post: https://community.humhub.com/content/perma?id=279398

Seams to be a database integrity issue.
However, it should still load, ignoring missing conversations.

The issue is the return type of `InboxMessagePreview::getMessage()` which is `Message` and, I think, should be changed to `?Message`.
But we need to check the consequences of this change.

Log:
```
TypeError: humhub\modules\mail\widgets\InboxMessagePreview::getMessage(): Return value must be of type humhub\modules\mail\models\Message, null returned in /var/www/html/carrotsocial/protected/modules/mail/widgets/InboxMessagePreview.php:59
Stack trace:
#0 /var/www/html/carrotsocial/protected/modules/mail/widgets/InboxMessagePreview.php(151): humhub\modules\mail\widgets\InboxMessagePreview->getMessage()
#1 /var/www/html/carrotsocial/protected/modules/mail/widgets/InboxMessagePreview.php(25): humhub\modules\mail\widgets\InboxMessagePreview->getLastEntry()
#2 /var/www/html/carrotsocial/protected/humhub/components/Widget.php(62): humhub\modules\mail\widgets\InboxMessagePreview->run()
#3 /var/www/html/carrotsocial/protected/modules/mail/views/mail/notificationList.php(10): humhub\components\Widget::widget()
#4 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#5 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile()
#6 /var/www/html/carrotsocial/protected/humhub/modules/ui/view/components/View.php(243): yii\base\View->renderFile()
#7 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/web/Controller.php(50): humhub\modules\ui\view\components\View->renderAjax()
#8 /var/www/html/carrotsocial/protected/modules/mail/controllers/MailController.php(208): yii\web\Controller->renderAjax()
#9 [internal function]: humhub\modules\mail\controllers\MailController->actionNotificationList()
#10 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#12 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#13 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#14 /var/www/html/carrotsocial/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#15 /var/www/html/carrotsocial/index.php(28): yii\base\Application->run()
#16 {main}
```

**Comment by luke-** [comment]
@yurabakhtin Can you explain why this happened? Shouldn't UserMessage onDelete check whether it is the last entry and, if necessary, also delete the message?

I would prefer it if the deletion worked reliably even without FKs. Then we can also delete related data, such as notifications, if necessary.

**Comment by yurabakhtin** [comment]
@luke- Ok, commit https://github.com/humhub/mail/pull/475/commits/a8349e88d831a1c90164fe37f804dd81909fd5a4

**Comment by luke-** [comment]
@optitsolutions Can you please upgrade to the latest mail version and rerun the integrity check. There should be some fixes. 
We couldn't find the root cause of this DB problem. 

If you find steps to reproduce the creation of corrupted entries, please let us know and reopen this.
